export const DIELINE_LIBRARY_ITEMS = [
  {
    id: "0201",
    code: "FEFCO 0201",
    name: "Standard RSC Box",
    category: "folding",
    source: "system",
    image2d: "/thumbnails/0201_2D.png",
    image3d: "/thumbnails/0201_3D.png",
    description:
      "Regular Slotted Container (FEFCO 0201). The most common shipping box type.",
    tags: ["Shipping", "Corrugated"],
    isNew: false,
  },
  {
    id: "0203",
    code: "FEFCO 0203",
    name: "Full Overlap Slotted Box",
    category: "folding",
    source: "system",
    image2d: "/thumbnails/0203_2D.png",
    image3d: "/thumbnails/0203_3D.png",
    description:
      "Full overlap flaps for extra stacking strength and protection.",
    tags: ["Heavy Duty", "Shipping"],
    isNew: false,
  },
  {
    id: "0301",
    code: "FEFCO 0301",
    name: "Telescope Box",
    category: "folding",
    source: "system",
    image2d: "/thumbnails/0301_2D.png",
    image3d: "/thumbnails/0301_3D.png",
    description:
      "Two-piece box with a separate lid and base for premium packaging.",
    tags: ["Retail", "Premium"],
    isNew: true,
  },
  {
    id: "0401",
    code: "FEFCO 0401",
    name: "Folder Type Box",
    category: "mailer",
    source: "system",
    image2d: "/thumbnails/0401_2D.png",
    image3d: "/thumbnails/0401_3D.png",
    description: "One-piece folder-style box that’s fast to assemble and ship.",
    tags: ["Mailer", "Lightweight"],
    isNew: false,
  },
  {
    id: "0427",
    code: "FEFCO 0427",
    name: "Double Wall Tuck Front",
    category: "mailer",
    source: "system",
    image2d: "/thumbnails/0427_2D.png",
    image3d: "/thumbnails/0427_3D.png",
    description:
      "Tuck-front mailer with double wall for stronger presentation.",
    tags: ["E-commerce", "Premium"],
    isNew: false,
  },
];

